Imports System.ComponentModel
Imports System.Text
Imports Transitions

Partial Public Class Rextonian
    Inherits DevExpress.XtraEditors.XtraForm
    Shared Sub New()
        '   DevExpress.UserSkins.BonusSkins.Register()
        DevExpress.Skins.SkinManager.EnableFormSkins()
    End Sub
    Public Sub New()
        InitializeComponent()
    End Sub

#Region " Translate"


#Region " Button click / Enter pressed"

    Private Sub me_English_KeyUp(sender As Object, e As KeyEventArgs) Handles me_English.KeyUp
        If e.KeyCode = Keys.Enter Then
            TranslatePressed()
        End If
    End Sub
    Private Sub but_Translate_Click(sender As Object, e As EventArgs) Handles but_Translate.Click
        TranslatePressed()
    End Sub

#End Region
#Region " Translate Code"

    Public Function Translate(EnglishWord As String, RextonianWord As String, source As String) As String

        Dim pattern As String = String.Format("\b{0}\b", EnglishWord)
        Return RegularExpressions.Regex.Replace(source, pattern, RextonianWord, RegularExpressions.RegexOptions.IgnoreCase)

    End Function


#End Region

#Region " Dictionary"
    Private Sub but_Add_Click(sender As Object, e As EventArgs) Handles but_Add.Click
        Dim DictionaryFile As String = Application.StartupPath + "\Rextonian.dic"

        Dim DictionaryString As String() = IO.File.ReadAllLines(DictionaryFile)

        Dim Englishword As String
        Dim Rextonianword As String



        Dim xform As New AddWord
        If xform.ShowDialog = DialogResult.OK Then
            Englishword = xform.tb_English.Text
            Rextonianword = xform.tb_Rextonian.Text
            IO.File.AppendAllText(DictionaryFile, Environment.NewLine & Englishword & "=" & Rextonianword)

        End If



    End Sub



    Dim EnglishText As String
    Public Sub TranslatePressed()
        EnglishText = me_English.Text
        ReadDictionary()
        StartPhrases()
        Dim s As String = EnglishText
        ' Dim ss As String = EnglishText

        '...Start First...

        ' s = s.Replace("ch", "CH")
        ' s = s.Replace("Ch", "CH")
        ' s = s.Replace("ck", "CK")
        ' s = s.Replace("ce", "s")
        ' s = s.Replace("c", "k")
        ' s = s.Replace("CH", "ch")

        '...Dictionary...
        '...Words that need translated first because of matching other words that are spelled them same when translated...
        s = Translate("too", "aldas", s)

        s = Translate("hello", "helaa", s) : s = Translate("hi", "helaa", s) : s = Translate("hey", "helaa", s) : s = Translate("howdy", "helaa", s)
        s = Translate("hiya", "helaa", s) : s = Translate("aloha", "helaa", s) : s = Translate("yo", "helaa", s)

        s = Translate("me", "ma", s)
        s = Translate("I'm", "maa", s)
        s = Translate("I", "ma", s)


        s = Translate("Im", "maa", s)
        s = Translate("am", "maa", s)
        s = Translate("my", "maa", s) : s = Translate("myself", "maa", s)
        s = Translate("mine", "maa", s)

        s = Translate("you", "yoo", s)
        s = Translate("your", "yoo", s)
        s = Translate("yours", "yoo", s)
        s = Translate("its", "too", s)
        s = Translate("they", "too", s)
        s = Translate("them", "too", s)
        s = Translate("their", "too", s)
        s = Translate("theirs", "too", s)
        s = Translate("we", "woo", s)
        s = Translate("our", "owroo", s)
        s = Translate("ours", "owroo", s)
        s = Translate("all", "aldoo", s)
        s = Translate("everyone", "aldoo", s)
        s = Translate("everybody", "aldoo", s)
        s = Translate("everything", "aldoo", s)
        s = Translate("anyone", "aldoo", s)
        s = Translate("anything", "aldoo", s)


        s = Translate("he", "hoo", s)
        s = Translate("him", "hoo", s)
        s = Translate("his", "hii", s) : s = Translate("hiself", "hii", s)
        s = Translate("boy", "booyoo", s)
        s = Translate("man", "aabooyoo", s)
        s = Translate("mr.", "aabooyoo", s)
        s = Translate("mr", "aabooyoo", s)
        s = Translate("mister", "aabooyoo", s)
        s = Translate("guy", "aabooyoo", s)
        s = Translate("brother", "herbooyoo", s)
        s = Translate("father", "fabooyoo", s)
        s = Translate("dad", "fabooyoo", s)
        s = Translate("papa", "fabooyoo", s)
        s = Translate("husband", "marbooyoo", s)
        s = Translate("groom", "marbooyoo", s)
        s = Translate("son", "booyoo", s)

        s = Translate("she", "Soo", s)
        s = Translate("her", "Soo", s)
        s = Translate("hers", "Sii", s) : s = Translate("herself", "Sii", s)
        s = Translate("girl", "greyoo", s)
        s = Translate("woman", "aagreyoo", s)
        s = Translate("mrs.", "aagreyoo", s)
        s = Translate("mrs", "aagreyoo", s)
        s = Translate("missus", "aagreyoo", s)
        s = Translate("gal", "aagreyoo", s)
        s = Translate("lady", "aagreyoo", s)
        s = Translate("sister", "hergreyoo", s)
        s = Translate("mother", "fagreyoo", s)
        s = Translate("mom", "fagreyoo", s)
        s = Translate("mama", "fagreyoo", s)
        s = Translate("wife", "margreyoo", s)
        s = Translate("bride", "margreyoo", s)
        s = Translate("daughter", "greyoo", s)

        s = Translate("parent", "fayoo", s)
        s = Translate("spouse", "maryoo", s)
        s = Translate("family", "martaaoo", s)
        s = Translate("ancestry", "martaaoo", s)
        s = Translate("pedigree", "martaaoo", s)
        s = Translate("descendant", "martaaoo", s)
        s = Translate("forefathers", "martaaoo", s)
        s = Translate("bloodline", "martaaoo", s)

        s = Translate("friend", "friigoo", s)
        s = Translate("amigo", "friigoo", s)
        s = Translate("companion", "friigoo", s)
        s = Translate("compadre", "friigoo", s)
        s = Translate("homeboy", "friigoo", s)
        s = Translate("homie", "friigoo", s)
        s = Translate("dawg", "friigoo", s)
        s = Translate("bff", "friigoo", s)

        s = Translate("it's", "deS", s)
        s = Translate("it", "deS", s)
        s = Translate("is", "deS", s)
        s = Translate("are", "deS", s)
        s = Translate("the", "deS", s)
        s = Translate("this", "deS", s)
        s = Translate("these", "deS", s)
        s = Translate("this is", "deS", s)
        s = Translate("that", "deS", s)
        s = Translate("has", "haSna", s)
        s = Translate("have", "havna", s)
        s = Translate("got", "ganaa", s)

        s = Translate("was", "wafuu", s)

        s = Translate("in", "en", s) : s = Translate("inside", "en", s)
        s = Translate("out", "oonra", s) : s = Translate("outside", "oonra", s)
        s = Translate("on", "en", s)
        s = Translate("at", "en", s) : s = Translate("into", "en", s) : s = Translate("for", "en", s)
        s = Translate("off", "dee", s)
        s = Translate("from", "dee", s)
        s = Translate("of", "dee", s)
        s = Translate("by", "dee", s)
        s = Translate("with", "won", s)
        s = Translate("about", "dee", s)
        s = Translate("said", "Sedoo", s)
        s = Translate("or", "e", s)
        s = Translate("either", "e", s)
        s = Translate("and", "y", s)
        s = Translate("do", "daa", s)

        s = Translate("if", "fii", s)
        s = Translate("suppose", "fii", s)


        s = Translate("cat", "kato", s) : s = Translate("kitty", "kato", s) : s = Translate("feline", "kato", s)
        s = Translate("chair", "cairya", s) : s = Translate("seat", "cairya", s)
        s = Translate("short", "soorToo", s)

        s = Translate("apart", "Sepaadoo", s)
        s = Translate("separate", "Sepaadoo", s)
        s = Translate("separated", "Sepaadoo", s)

        ' s = Translate("no", "noo", s)
        s = Translate("speak", "Speklar", s)
        s = Translate("speaking", "Speklar", s)
        s = Translate("talk", "Speklar", s)
        s = Translate("talking", "Speklar", s)
        s = Translate("told", "Speklar", s)
        s = Translate("tell", "Speklar", s)
        s = Translate("telling", "Speklar", s)
        s = Translate("really", "reladad", s)
        s = Translate("basically", "reladad", s)
        s = Translate("same", "Semo", s)
        s = Translate("different", "difeeinTa", s)
        s = Translate("difference", "difeeinTa", s)
        s = Translate("voice", "vookoo", s)
        s = Translate("pronounce", "vookoo", s)
        s = Translate("vocal", "vookoo", s)
        s = Translate("little", "lil", s)
        s = Translate("small", "lil", s)
        s = Translate("bit", "lil", s)
        s = Translate("rely", "relar", s)
        s = Translate("relies", "relarS", s)
        s = Translate("depend", "relar", s)
        s = Translate("new", "newvoo", s)
        s = Translate("look", "lkra", s)
        s = Translate("see", "lkra", s)
        s = Translate("a", "aa", s)
        s = Translate("to", "a", s)
        s = Translate("as", "a", s)
        s = Translate("save", "Savar", s)
        s = Translate("savior", "Savaroo", s)
        s = Translate("saving", "savar", s)
        s = Translate("nothing", "notda", s)
        s = Translate("none", "notda", s)
        s = Translate("zero", "notda", s)
        s = Translate("naught", "notda", s)
        s = Translate("nought", "notda", s)
        s = Translate("zlich", "notda", s)
        s = Translate("nada", "notda", s)
        s = Translate("first", "firSTero", s)
        s = Translate("originally", "firSTero", s)
        s = Translate("initial", "firstero", s)
        s = Translate("thought", "thawento", s)
        s = Translate("think", "thawento", s)
        s = Translate("consider", "thawento", s)
        s = Translate("regard", "thawento", s)
        s = Translate("reality", "relitad", s)
        s = Translate("real", "relitad", s)
        s = Translate("try", "Triitar", s)
        s = Translate("move", "moovToo", s)
        s = Translate("past", "pasda", s)
        s = Translate("former", "pasda", s)
        s = Translate("preceding", "pasda", s)
        s = Translate("but", "baadoo", s)
        s = Translate("just", "baadoo", s)
        s = Translate("yet", "baadoo", s)
        s = Translate("nevertheless", "baadoo", s)
        s = Translate("nonetheless", "baadoo", s)
        s = Translate("however", "baadoo", s)
        s = Translate("though", "baadoo", s)
        s = Translate("notwithstanding", "baadoo", s)
        s = Translate("despite", "baadoo", s)

        s = Translate("come", "komen", s)
        s = Translate("comes", "komen", s)
        s = Translate("haunt", "huwnTrida", s)
        s = Translate("scare", "huwnTrida", s)
        s = Translate("fright", "huwnTrida", s)
        s = Translate("startle", "huwnTrida", s)
        s = Translate("afraid", "huwnTrida", s)
        s = Translate("fear", "huwnTrida", s)
        s = Translate("fearful", "huwnTrida", s)
        s = Translate("fraction", "fraakparTaa", s)
        s = Translate("part", "fraakparTaa", s)
        s = Translate("enter", "enTr", s)
        s = Translate("enters", "enTrS", s)
        s = Translate("another", "aanTroo", s)
        s = Translate("other", "aanTroo", s)
        s = Translate("anothers", "aanTrooS", s)
        s = Translate("others", "aanTrooS", s)
        s = Translate("else", "aanTroo", s)
        s = Translate("learn", "lerndaa", s)
        s = Translate("learns", "lerndaa", s)
        s = Translate("learning", "lerndaa", s)
        s = Translate("fast", "faSidoo", s) : s = Translate("quick", "faSidoo", s) : s = Translate("quickly", "faSidoo", s) : s = Translate("rapid", "faSidoo", s)
        s = Translate("rapidly", "faSidoo", s) : s = Translate("swift", "faSidoo", s) : s = Translate("speedily", "faSidoo", s) : s = Translate("briskly", "faSidoo", s)
        s = Translate("hurry", "faSidoo", s) : s = Translate("sudden", "faSidoo", s) : s = Translate("suddenly", "faSidoo", s)
        s = Translate("slow", "sloota", s) : s = Translate("unhurry", "sloota", s) : s = Translate("steady", "sloota", s) : s = Translate("sluggish", "sloota", s)
        s = Translate("gone", "gondoo", s)
        s = Translate("absent", "gondoo", s)
        s = Translate("missing", "gondoo", s)
        s = Translate("unavailable", "gondoo", s)
        s = Translate("away", "gondoo", s)
        s = Translate("abroad", "gondoo", s)
        s = Translate("far", "farho", s)
        s = Translate("distant", "farho", s)
        s = Translate("faraway", "farho", s)
        s = Translate("question", "qeSuunTa", s)
        s = Translate("ask", "qeSuunTa", s)
        s = Translate("interview", "qeSuunTa", s)
        s = Translate("arise", "aariiSger", s)
        s = Translate("rises", "aariiSger", s)
        s = Translate("unstoppable", "imSTuparb", s)
        s = Translate("indomitable", "imSTuparb", s)
        s = Translate("unbeatable", "imSTuparb", s)
        s = Translate("invincible", "imSTuparb", s)
        s = Translate("indomitable", "imSTuparb", s)
        s = Translate("irrepressible", "imSTuparb", s)
        s = Translate("supreme", "imSTuparb", s)
        s = Translate("inextinguishable", "imSTuparb", s)
        s = Translate("inexorable", "imSTuparb", s)
        s = Translate("uncontrollable", "imSTuparb", s)
        s = Translate("stop", "STupnar", s)
        s = Translate("stoppage", "STupnar", s)
        s = Translate("cease", "STupnar", s)
        s = Translate("terminate", "STupnar", s)
        s = Translate("halt", "STupnar", s)
        s = Translate("stay", "STedar", s)
        s = Translate("go", "galaar", s)
        s = Translate("be", "galaar", s)
        s = Translate("let", "galaar", s)
        s = Translate("leave", "galaar", s)
        s = Translate("villain", "vilanaaloo", s)
        s = Translate("evil", "vilanaaloo", s)

        s = Translate("good", "guuna", s)
        s = Translate("kind", "guuna", s)
        s = Translate("fine", "guuna", s)
        s = Translate("behave", "gaguuna", s)
        s = Translate("bad", "bala", s)
        s = Translate("misbehave", "gabala", s)
        s = Translate("naughty", "gabala", s)
        s = Translate("disobey", "gabala", s)
        s = Translate("disobedient", "gabala", s)
        s = Translate("oh", "oo", s)
        s = Translate("ok", "oo", s)
        s = Translate("okay", "oo", s)

        s = Translate("much", "mucoo", s)
        s = Translate("many", "mucoo", s)
        s = Translate("very", "mucoo", s)
        s = Translate("lot", "mucoo", s)
        s = Translate("great", "guunaoo", s)
        s = Translate("huge", "guunaoo", s)
        s = Translate("enormous", "guunaoo", s)
        s = Translate("big", "gunaoo", s)
        s = Translate("large", "gunaoo", s)
        s = Translate("spacious", "gunaoo", s)
        s = Translate("vast", "gunaoo", s)
        s = Translate("brawny", "gunaoo", s)
        s = Translate("bigger", "gunaoor", s)
        s = Translate("greater", "gunaoor", s)
        s = Translate("most", "mooaas", s)
        s = Translate("majority", "mooaas", s)
        s = Translate("more", "mooaas", s)
        s = Translate("plus", "mooaas", s)
        s = Translate("less", "amooaas", s)
        s = Translate("least", "amooaas", s)
        s = Translate("smallest", "amooaas", s)
        s = Translate("minutest", "amooaas", s)
        s = Translate("tiniest", "amooaas", s)
        s = Translate("littlest", "amooaas", s)


        s = Translate("name", "nembraa", s)
        s = Translate("nice", "niiSdaab", s)
        s = Translate("meet", "meerS", s)
        s = Translate("meeting", "meerSa", s)
        s = Translate("thanks", "TaanSeeaS", s)
        '   s = Translate("thank you", "taanseeas", s)
        '   s = Translate("you're welcome", "welda", s)
        s = Translate("sorry", "SoorenToo", s)
        s = Translate("apologize", "SoorenToo", s)
        s = Translate("yes", "ya", s)
        s = Translate("yeah", "ya", s)
        s = Translate("yea", "ya", s)
        s = Translate("yep", "ya", s)
        s = Translate("yup", "ya", s)
        s = Translate("no", "na", s)
        s = Translate("not", "na", s)
        s = Translate("nope", "na", s)
        s = Translate("nay", "na", s)
        s = Translate("not", "daana", s)
        s = Translate("don't", "daana", s)
        s = Translate("dont", "daana", s)
        s = Translate("how", "hoomaS", s)
        s = Translate("understand", "undrendoo", s)

        s = Translate("who", "huu", s)
        s = Translate("what", "kaa", s)

        s = Translate("when", "wendoo", s)
        s = Translate("where", "werndoo", s)
        s = Translate("why", "kaadoo", s)
        s = Translate("because", "kaadoo", s)
        s = Translate("cause", "kaadoo", s)
        s = Translate("cuz", "kaadoo", s)
        s = Translate("bye", "biiooS", s)
        s = Translate("goodbye", "biiooS", s)

        s = Translate("planet", "planTa", s)
        s = Translate("live", "leevr", s)
        s = Translate("exist", "leevr", s)
        s = Translate("life", "leeda", s)
        s = Translate("die", "naleeda", s)
        s = Translate("dead", "naleeda", s)
        s = Translate("death", "naleeda", s)
        s = Translate("died", "naleeda", s)
        s = Translate("here", "heearna", s)
        s = Translate("hither", "heearna", s)
        s = Translate("there", "aheearna", s)
        s = Translate("yonder", "aheearna", s)
        s = Translate("area", "arna", s)
        s = Translate("district", "arna", s)
        s = Translate("region", "arna", s)
        s = Translate("zone", "arna", s)
        s = Translate("sector", "arna", s)
        s = Translate("locality", "arna", s)
        s = Translate("locale", "arna", s)
        s = Translate("local", "arna", s)
        s = Translate("neighborhood", "arna", s)

        s = Translate("find", "fiindar", s)
        s = Translate("found", "fiindar", s)
        s = Translate("discover", "fiindar", s)
        s = Translate("discovered", "fiindar", s)
        s = Translate("unconver", "fiindar", s)
        s = Translate("unwrap", "fiindar", s)

        s = Translate("wander", "wandlar", s)
        s = Translate("lurk", "wandlar", s)
        s = Translate("lurking", "wandlar", s)
        s = Translate("wandering", "wandlar", s)
        s = Translate("world", "woorunda", s)
        s = Translate("fate", "faaTenoo", s)
        s = Translate("future", "faaTenoo", s)
        s = Translate("within", "en", s)
        s = Translate("travel", "Trevlar", s)
        s = Translate("journey", "Trevlar", s)
        s = Translate("now", "nowra", s)
        s = Translate("modern", "nowra", s)
        s = Translate("only", "onTa", s)
        s = Translate("begin", "beegezar", s)
        s = Translate("begins", "beegezar", s)
        s = Translate("beginning", "beegezar", s)
        s = Translate("establish", "beegezar", s)
        s = Translate("start", "beegezar", s)
        s = Translate("starts", "beegezar", s)

        s = Translate("originate", "beegezar", s)
        s = Translate("originates", "beegezar", s)
        s = Translate("become", "beekezar", s)
        s = Translate("long", "looga", s)
        s = Translate("history", "hiira", s)
        s = Translate("hour", "oora", s)
        s = Translate("time", "Tiira", s)
        s = Translate("period", "Tiira", s)
        s = Translate("minute", "menuta", s)
        s = Translate("month", "mesa", s)
        s = Translate("early", "tiisa", s)
        s = Translate("ago", "agaaSa", s)
        s = Translate("day", "diiaa", s)
        s = Translate("daytime", "diiaa", s)
        s = Translate("morning", "moorna", s)
        s = Translate("afternoon", "aafTarda", s)
        s = Translate("noon", "tarda", s)
        s = Translate("night", "niika", s)
        s = Translate("evening", "niika", s)
        s = Translate("dark", "niika", s)
        s = Translate("pitchy", "niika", s)
        s = Translate("gloomy", "niika", s)
        s = Translate("dusky", "niika", s)
        s = Translate("shadow", "niika", s)
        s = Translate("shadowy", "niika", s)
        s = Translate("underlit", "niika", s)
        s = Translate("dim", "niika", s)
        s = Translate("unilluminated", "niika", s)
        s = Translate("unlit", "niika", s)
        s = Translate("darkness", "niika", s)
        s = Translate("twilght", "niika", s)
        s = Translate("shade", "niika", s)
        s = Translate("ability", "aabilad", s)
        s = Translate("power", "aabilad", s)
        s = Translate("superpower", "aabilad", s)
        s = Translate("able", "aablr", s)
        s = Translate("can", "aablr", s)
        s = Translate("may", "aablr", s)
        s = Translate("maybe", "aablroo", s)
        s = Translate("perhaps", "aablroo", s)
        s = Translate("might", "aablroo", s)
        s = Translate("could", "aablr", s)
        s = Translate("high", "aabusma", s)
        s = Translate("up", "aabusma", s)
        s = Translate("above", "aabusma", s)
        s = Translate("upward", "aabusma", s)
        s = Translate("upwards", "aabusma", s)
        s = Translate("down", "naabusma", s)
        s = Translate("low", "naabusma", s)
        s = Translate("downwards", "naabusma", s)
        s = Translate("accept", "aaseptr", s)
        s = Translate("according", "akormee", s)
        s = Translate("accordingly", "akormee", s)
        s = Translate("account", "akoonta", s)
        s = Translate("across", "atrevlar", s)
        s = Translate("over", "atrevlar", s)
        s = Translate("skip", "atrevlar", s)
        s = Translate("perform", "aktoo", s)
        s = Translate("act", "aktoo", s)
        s = Translate("action", "aktoo", s)
        s = Translate("activity", "aktoo", s)
        s = Translate("behavior", "aktoo", s)
        s = Translate("conduct", "aktoo", s)
        s = Translate("manner", "aktoo", s)
        s = Translate("manners", "aktoo", s)
        s = Translate("actually", "eevkluusoo", s)
        s = Translate("even", "eevkluusoo", s)
        s = Translate("add", "adr", s)
        s = Translate("address", "adreson", s)
        s = Translate("direction", "adreson", s)
        s = Translate("admin", "admoon", s)
        s = Translate("administration", "admoon", s)
        s = Translate("management", "admoon", s)
        s = Translate("executive", "admoon", s)
        s = Translate("manager", "admoon", s)
        s = Translate("boss", "admoon", s)
        s = Translate("admit", "admetr", s)
        s = Translate("adult", "adaltee", s)
        s = Translate("mayor", "adaltee", s)
        s = Translate("grown-up", "adaltee", s)
        s = Translate("affect", "aafektr", s)
        s = Translate("before", "beefda", s)
        s = Translate("previous", "beefda", s)
        s = Translate("previously", "beefda", s)
        s = Translate("earlier", "beefda", s)
        s = Translate("prior", "beefda", s)
        s = Translate("after", "aaf", s)
        s = Translate("again", "agavza", s)
        s = Translate("against", "upoosrsa", s)
        s = Translate("oppose", "upoosrsa", s)
        s = Translate("opposed", "upoosrsa", s)
        s = Translate("generation", "aajoosa", s)
        s = Translate("age", "aajoosa", s)
        s = Translate("old", "aajoosa", s)
        s = Translate("young", "joosa", s)
        s = Translate("agency", "aagensa", s)
        s = Translate("organization", "aagensa", s)
        s = Translate("business", "aagensa", s)
        s = Translate("company", "aagensa", s)
        s = Translate("bereau", "aagensa", s)
        s = Translate("industry", "aagensa", s)
        s = Translate("agent", "aagensoo", s)
        s = Translate("representative", "aagensoo", s)
        s = Translate("businessman", "aagensoo", s)
        s = Translate("businesswoman", "aagensoo", s)
        s = Translate("businessmen", "aagensoo", s)
        s = Translate("emissary", "aagensoo", s)
        s = Translate("broker", "aagensoo", s)
        s = Translate("spokesperson", "aagensoo", s)
        s = Translate("spokesman", "aagensoo", s)
        s = Translate("spokeswoman", "aagensoo", s)
        s = Translate("officer", "aagensoo", s)
        s = Translate("offical", "aagensoo", s)
        s = Translate("police", "aagensoo", s)
        s = Translate("enforcer", "aagensoo", s)
        s = Translate("authorities", "aagensoo", s)
        s = Translate("policeman", "aagensoo", s)
        s = Translate("policewoman", "aagensoo", s)
        s = Translate("agree", "agrdoo", s)
        s = Translate("agreement", "agrdoo", s)
        s = Translate("deal", "agrdoo", s)
        s = Translate("arrangement", "agrdoo", s)
        s = Translate("bargain", "agrdoo", s)
        s = Translate("concur", "agrdoo", s)
        s = Translate("consent", "agrdoo", s)
        s = Translate("air", "ehree", s)
        s = Translate("aura", "ehree", s)
        s = Translate("gas", "ehree", s)
        s = Translate("oxygen", "ehree", s)
        s = Translate("allow", "prmetar", s)
        s = Translate("permit", "prmetar", s)
        s = Translate("permitted", "prmetar", s)
        s = Translate("allowed", "prmetar", s)
        s = Translate("almost", "almesa", s)
        s = Translate("nearly", "almesa", s)
        s = Translate("near", "almesa", s)
        s = Translate("practically", "almesa", s)
        s = Translate("virtually", "almesa", s)
        s = Translate("roughly", "almesa", s)
        s = Translate("approach", "almesa", s)
        s = Translate("approaching", "almesa", s)
        s = Translate("alone", "alsoo", s)
        s = Translate("single", "alsoo", s)
        s = Translate("along", "alorgoo", s)
        s = Translate("already", "alya", s)
        s = Translate("also", "aldas", s)
        s = Translate("likewise", "aldas", s)
        s = Translate("equally", "aldas", s)
        s = Translate("although", "althkaa", s)
        s = Translate("always", "alwepraa", s)
        s = Translate("among", "amontr", s)
        s = Translate("amount", "amoodad", s)
        s = Translate("analysis", "eksemr", s)
        s = Translate("examine", "eksemr", s)
        s = Translate("examination", "eksemr", s)
        s = Translate("investigation", "eksemr", s)
        s = Translate("inspect", "eksemr", s)
        s = Translate("inspection", "eksemr", s)
        s = Translate("survey", "eksemr", s)
        s = Translate("study", "eksemr", s)
        s = Translate("research", "eksemr", s)
        s = Translate("review", "eksemr", s)
        s = Translate("evaluate", "eksemr", s)
        s = Translate("evaluation", "eksemr", s)
        s = Translate("interpretation", "eksemr", s)
        s = Translate("dissection", "eksemr", s)
        s = Translate("disect", "eksemr", s)
        s = Translate("probe", "eksemr", s)
        s = Translate("animal", "anemel", s)
        s = Translate("answer", "ansondr", s)
        s = Translate("reply", "ansondr", s)
        s = Translate("response", "ansondr", s)
        s = Translate("comeback", "ansondr", s)
        s = Translate("retort", "ansondr", s)
        s = Translate("reaction", "ansondr", s)
        s = Translate("any", "anuuna", s)
        s = Translate("appear", "apeesar", s)
        s = Translate("visible", "apeesar", s)
        s = Translate("reveal", "apeesar", s)
        s = Translate("manifest", "apeesar", s)
        s = Translate("emerge", "apeesar", s)
        s = Translate("apply", "apliisr", s)
        s = Translate("application", "apliisr", s)
        s = Translate("approach", "aprookaa", s)
        s = Translate("method", "aprookaa", s)
        s = Translate("procedure", "aprookaa", s)
        s = Translate("strategy", "aprookaa", s)
        s = Translate("technique", "aprookaa", s)
        s = Translate("tactic", "aprookaa", s)
        s = Translate("style", "aprookaa", s)
        s = Translate("argue", "naagrdoo", s)
        s = Translate("quarrel", "naagrdoo", s)
        s = Translate("disagree", "naagrdoo", s)
        s = Translate("squabble", "naagrdoo", s)
        s = Translate("bicker", "naagrdoo", s)
        s = Translate("dispute", "naagrdoo", s)
        s = Translate("debate", "naagrdoo", s)
        s = Translate("wrangle", "naagrdoo", s)
        s = Translate("arm", "arazoo", s)
        s = Translate("around", "arsoona", s)
        s = Translate("arrive", "ariigra", s)
        s = Translate("art", "rtaa", s)
        s = Translate("craft", "rtaa", s)
        s = Translate("graphic", "rtaa", s)
        s = Translate("artist", "rtaaoo", s)
        s = Translate("assume", "asuumr", s)
        s = Translate("presume", "asuumr", s)
        s = Translate("conclude", "asuumr", s)
        s = Translate("deduce", "asuumr", s)
        s = Translate("infer", "asuumr", s)
        s = Translate("reckon", "asuumr", s)
        s = Translate("reason", "asuumr", s)
        s = Translate("believe", "asuumr", s)
        s = Translate("guess", "asuumr", s)
        s = Translate("estimate", "asuumr", s)
        s = Translate("speculate", "asuumr", s)
        s = Translate("speculation", "asuumr", s)
        s = Translate("hypothesis", "asuumr", s)
        s = Translate("theory", "asuumr", s)
        s = Translate("theorize", "asuumr", s)
        s = Translate("conject", "asuumr", s)
        s = Translate("postulation", "asuumr", s)
        s = Translate("attack", "atakaa", s)
        s = Translate("assault", "atakaa", s)
        s = Translate("abuse", "atakaa", s)
        s = Translate("onslaught", "atakaa", s)
        s = Translate("strike", "atakaa", s)
        s = Translate("charge", "atakaa", s)
        s = Translate("pounce", "atakaa", s)
        s = Translate("attention", "atensoon", s)
        s = Translate("notice", "atensoon", s)
        s = Translate("note", "atensoon", s)
        s = Translate("observe", "atensoon", s)
        s = Translate("law", "lawaa", s)
        s = Translate("legal", "lawaa", s)
        s = Translate("attorney", "lawaaoo", s)
        s = Translate("lawyer", "lawaaoo", s)
        s = Translate("counselor", "lawaaoo", s)
        s = Translate("audience", "peetaaoo", s)
        s = Translate("crowd", "peetaaoo", s)
        s = Translate("congregation", "peetaaoo", s)
        s = Translate("viewers", "peetaaoo", s)
        s = Translate("people", "peetaaoo", s)
        s = Translate("community", "peetaaoo", s)
        s = Translate("human", "peetaa", s)
        s = Translate("person", "peetaa", s)
        s = Translate("citizen", "peetaa", s)
        s = Translate("participant", "peetaa", s)
        s = Translate("member", "peetaa", s)
        s = Translate("character", "peetaa", s)
        s = Translate("individual", "peetaa", s)
        s = Translate("writer", "bokrooroo", s)
        s = Translate("book", "bokroo", s)
        s = Translate("page", "pokrooa", s)
        s = Translate("paper", "pokrooa", s)
        s = Translate("magazine", "bokroo", s)
        s = Translate("author", "bokrooroo", s)
        s = Translate("novelist", "bokrooroo", s)
        s = Translate("playwright", "bokrooroo", s)
        s = Translate("poet", "bokrooroo", s)
        s = Translate("essayist", "bokrooroo", s)
        s = Translate("biographer", "bokrooroo", s)
        s = Translate("authority", "ruugla", s)
        s = Translate("command", "ruugla", s)
        s = Translate("order", "ruugla", s)
        s = Translate("dominance", "ruugla", s)
        s = Translate("rule", "ruugla", s)
        s = Translate("control", "ruugla", s)
        s = Translate("manage", "ruugla", s)
        s = Translate("govern", "ruugla", s)
        s = Translate("overpower", "ruugla", s)
        s = Translate("supremacy", "ruugla", s)
        s = Translate("sovereignty", "ruugla", s)
        s = Translate("ruler", "ruuglaoo", s)
        s = Translate("leader", "ruuglaoo", s)
        s = Translate("available", "avaaelnee", s)
        s = Translate("obtainable", "avaaelnee", s)
        s = Translate("accessible", "avaaelnee", s)
        s = Translate("untaken", "avaaelnee", s)
        s = Translate("unused", "avaaelnee", s)
        s = Translate("gettable", "avaaelnee", s)
        s = Translate("obtain", "getaanar", s)
        s = Translate("get", "getaanar", s)
        s = Translate("aquire", "getaanar", s)
        s = Translate("receive", "getaanar", s)
        s = Translate("gain", "getaanar", s)
        s = Translate("procure", "getaanar", s)
        s = Translate("attain", "getaanar", s)
        s = Translate("avoid", "aveetar", s)
        s = Translate("reject", "aveetar", s)
        s = Translate("abstain", "aveetar", s)
        s = Translate("refrain", "aveetar", s)
        s = Translate("baby", "baabaa", s)
        s = Translate("child", "baayoo", s)
        s = Translate("kid", "baayoo", s)
        s = Translate("children", "baayoo", s)
        s = Translate("back", "bakdraas", s)
        s = Translate("rear", "bakdraas", s)
        s = Translate("hind", "bakdraas", s)
        s = Translate("backmost", "bakdraas", s)
        s = Translate("behind", "", s)
        s = Translate("hinder", "bakdraas", s)
        s = Translate("return", "reegraas", s)
        s = Translate("bag", "baasoo", s)
        s = Translate("ball", "boolaa", s)
        s = Translate("bank", "boonkaa", s)
        s = Translate("bar", "bad", s)
        s = Translate("rod", "bad", s)
        s = Translate("stick", "bad", s)
        s = Translate("shaft", "bad", s)
        s = Translate("base", "funsdaa", s)
        s = Translate("foundation", "funsdaa", s)
        s = Translate("beat", "hepraa", s)
        s = Translate("strike", "hepraa", s)
        s = Translate("hit", "hepraa", s)
        s = Translate("bang", "hepraa", s)
        s = Translate("punch", "hepraa", s)
        s = Translate("knock", "hepraa", s)
        s = Translate("whack", "hepraa", s)
        s = Translate("wallop", "hepraa", s)
        s = Translate("bash", "hepraa", s)
        s = Translate("beautiful", "beemosoo", s)
        s = Translate("pretty", "beemosoo", s)
        s = Translate("gorgeous", "beemosoo", s)
        s = Translate("handsome", "beemosoo", s)
        s = Translate("attractive", "beemosoo", s)
        s = Translate("good-looking", "beemosoo", s)
        s = Translate("lovely", "beemosoo", s)
        s = Translate("charming", "beemosoo", s)
        s = Translate("stunning", "beemosoo", s)
        s = Translate("elegant", "beemosoo", s)
        s = Translate("exquisite", "beemosoo", s)
        s = Translate("magnificent", "beemosoo", s)
        s = Translate("beauteous", "beemosoo", s)
        s = Translate("divine", "beemosoo", s)
        s = Translate("bewitching", "beemosoo", s)
        s = Translate("bed", "bema", s)
        s = Translate("cot", "bema", s)
        s = Translate("crib", "bema", s)
        s = Translate("canopy", "bema", s)
        s = Translate("waterbed", "bema", s)
        s = Translate("futon", "bema", s)
        s = Translate("benefit", "advenha", s)
        s = Translate("sake", "advenha", s)
        s = Translate("advantage", "advenha", s)
        s = Translate("convenience", "advenha", s)
        s = Translate("best", "besor", s)
        s = Translate("greatest", "besor", s)
        s = Translate("premier", "besor", s)
        s = Translate("premium", "besor", s)
        s = Translate("perfect", "besor", s)
        s = Translate("ultimate", "besor", s)
        s = Translate("better", "besor", s)
        s = Translate("superior", "besor", s)
        s = Translate("finer", "besor", s)
        s = Translate("preferable", "besor", s)
        s = Translate("between", "betna", s)
        s = Translate("beyond", "beeaya", s)
        s = Translate("bill", "belta", s)
        s = Translate("invoice", "belta", s)
        s = Translate("statement", "belta", s)
        s = Translate("billion", "1,000,000,000", s)
        s = Translate("black", "blagra", s)
        s = Translate("white", "wiika", s)
        s = Translate("blue", "buuzul", s)
        s = Translate("green", "greedaa", s)
        s = Translate("red", "rehoo", s)
        s = Translate("orange", "orenha", s)
        s = Translate("violet", "prepura", s)
        s = Translate("purple", "prepura", s)
        s = Translate("blood", "blagra", s)
        s = Translate("board", "wudra", s)
        s = Translate("plank", "wudra", s)
        s = Translate("timber", "wudra", s)
        s = Translate("wood", "wudra", s)
        s = Translate("woods", "forkaa", s)
        s = Translate("forest", "forkaa", s)
        s = Translate("woodland", "forkaa", s)
        s = Translate("timberland", "forkaa", s)
        s = Translate("jungle", "forkaa", s)
        s = Translate("body", "bupoo", s)
        s = Translate("form", "bupoo", s)
        s = Translate("anatomy", "bupoo", s)
        s = Translate("born", "boodoo", s)
        s = Translate("both", "boothoo", s)
        s = Translate("box", "baha", s)
        s = Translate("case", "baha", s)
        s = Translate("packet", "baha", s)
        s = Translate("carton", "baha", s)
        s = Translate("crate", "baha", s)
        s = Translate("casket", "baha", s)
        s = Translate("container", "baha", s)
        s = Translate("receptacle", "baha", s)
        s = Translate("coffin", "baha", s)
        s = Translate("coffer", "baha", s)
        s = Translate("canister", "baha", s)
        s = Translate("break", "braansoo", s)
        s = Translate("shatter", "braansoo", s)
        s = Translate("crack", "braansoo", s)
        s = Translate("fracture", "braansoo", s)
        s = Translate("burst", "braansoo", s)
        s = Translate("bust", "braansoo", s)
        s = Translate("bring", "breer", s)
        s = Translate("convey", "breer", s)
        s = Translate("carry", "breer", s)
        s = Translate("lift", "breer", s)
        s = Translate("lug", "breer", s)
        s = Translate("brought", "breer", s)
        s = Translate("budget", "bupestoo", s)
        s = Translate("finances", "bupestoo", s)
        s = Translate("finance", "bupest", s)
        s = Translate("money", "bupest", s)
        s = Translate("fund", "bupest", s)
        s = Translate("afford", "bupestoo", s)
        s = Translate("affordable", "bupestoo", s)
        s = Translate("build", "buutr", s)
        s = Translate("construct", "buutr", s)
        s = Translate("erect", "buutr", s)
        s = Translate("built", "buutr", s)
        s = Translate("erected", "buutr", s)
        s = Translate("constructed", "buutr", s)
        s = Translate("assemble", "buutr", s)
        s = Translate("make", "buutr", s)
        s = Translate("create", "buutr", s)
        s = Translate("design", "buutr", s)
        s = Translate("draw", "buutr", s)
        s = Translate("building", "strukera", s)
        s = Translate("structure", "strukera", s)
        s = Translate("job", "woohoo", s)
        s = Translate("work", "woohoo", s)
        s = Translate("worker", "woohooaa", s)
        s = Translate("employee", "woohooaa", s)
        s = Translate("career", "woohoo", s)
        s = Translate("effort", "woohoo", s)
        s = Translate("buy", "biiar", s)
        s = Translate("pay", "paaga", s)
        s = Translate("purchase", "biiar", s)
        s = Translate("invest", "biiar", s)
        s = Translate("call", "kaayada", s)
        s = Translate("yell", "yeeyada", s)
        s = Translate("holler", "yeeyada", s)
        s = Translate("shout", "yeeyada", s)
        s = Translate("howl", "yeeyada", s)
        s = Translate("yowl", "yeeyada", s)
        s = Translate("scream", "yeeyada", s)
        s = Translate("shriek", "yeeyada", s)
        s = Translate("screech", "yeeyada", s)
        s = Translate("roar", "yeeyada", s)
        s = Translate("yelp", "yeeyada", s)
        s = Translate("camera", "kemarra", s)
        s = Translate("campaign", "kempaanya", s)
        s = Translate("cancer", "balasekdad", s)
        s = Translate("hospital", "sekdadra", s)
        s = Translate("infirmary", "sekdadra", s)
        s = Translate("hospice", "sekdadra", s)
        s = Translate("health", "nasekdad", s)
        s = Translate("healthy", "nasekdad", s)
        s = Translate("well-being", "nasekdad", s)
        s = Translate("healthiness", "nasekdad", s)
        s = Translate("fitness", "nasekdad", s)
        s = Translate("wellness", "nasekdad", s)
        s = Translate("sick", "sekdad", s)
        s = Translate("sickness", "sekdad", s)
        s = Translate("ill", "sekdad", s)
        s = Translate("illness", "sekdad", s)
        s = Translate("disease", "balasekdad", s)
        s = Translate("ailment", "sekdad", s)
        s = Translate("infection", "sekdad", s)
        s = Translate("nausea", "sekdad", s)
        s = Translate("quease", "sekdad", s)
        s = Translate("queasiness", "sekdad", s)
        s = Translate("candidate", "kandetoo", s)
        s = Translate("capital", "goomoon", s)
        s = Translate("government", "goomoon", s)
        s = Translate("federal", "goomoon", s)
        s = Translate("congress", "goomoon", s)
        s = Translate("car", "astriiloo", s)
        s = Translate("vehicle", "astriiloo", s)
        s = Translate("automobile", "astriiloo", s)
        s = Translate("ship", "astriiloo", s)
        s = Translate("spacecraft", "astriiloo", s)
        s = Translate("rocket", "astriiloo", s)
        s = Translate("shuttle", "astriiloo", s)
        s = Translate("card", "kaaheta", s)
        s = Translate("care", "kiidoo", s)
        s = Translate("gentle", "kiidoo", s)
        s = Translate("safekeeping", "kiidoo", s)
        s = Translate("protection", "kiidoo", s)
        s = Translate("protect", "kiidoo", s)
        s = Translate("concern", "kiidoo", s)
        s = Translate("consideration", "kiidoo", s)
        s = Translate("regard", "kiidoo", s)
        s = Translate("catch", "gruura", s)
        s = Translate("grab", "gruura", s)
        s = Translate("cell", "rooshon", s)
        s = Translate("room", "rooshon", s)
        s = Translate("office", "rooshon", s)
        s = Translate("chamber", "rooshon", s)
        s = Translate("dungeon", "rooshon", s)
        s = Translate("center", "medeeoo", s)
        s = Translate("middle", "medeeoo", s)
        s = Translate("central", "medeeoo", s)
        s = Translate("mid", "medeeoo", s)
        s = Translate("midway", "medeeoo", s)
        s = Translate("medium", "medeeoo", s)
        s = Translate("medial", "medeeoo", s)
        s = Translate("mediam", "medeeoo", s)
        s = Translate("halfway", "medeeoo", s)
        s = Translate("half", "medeeoo", s)
        s = Translate("century", "senlooa", s)
        s = Translate("indeed", "suuro", s)
        s = Translate("assuredly", "suuro", s)
        s = Translate("certain", "suuro", s)
        s = Translate("certainly", "suuro", s)
        s = Translate("sure", "suuro", s)
        s = Translate("surely", "suuro", s)
        s = Translate("definite", "suuro", s)
        s = Translate("unquestionable", "suuro", s)
        s = Translate("indisputable", "suuro", s)
        s = Translate("obvious", "suuro", s)
        s = Translate("apparent", "suuro", s)
        s = Translate("apparently", "suuro", s)

        s = Translate("undeniable", "suuro", s)
        s = Translate("irrefutable", "suuro", s)
        s = Translate("evident", "suuro", s)
        s = Translate("unquestioned", "suuro", s)
        s = Translate("bound", "suuro", s)
        s = Translate("assured", "suuro", s)
        s = Translate("indubitable", "suuro", s)
        s = Translate("confirmed", "suuro", s)
        s = Translate("undoubted", "suuro", s)
        s = Translate("guaranteed", "suuro", s)
        s = Translate("unfailing", "suuro", s)
        s = Translate("infallible", "suuro", s)
        s = Translate("sure-fire", "suuro", s)
        s = Translate("challenge", "chetroo", s)
        s = Translate("difficult", "chetroo", s)
        s = Translate("difficultly", "chetroo", s)
        s = Translate("chance", "upoordad", s)
        s = Translate("opportunity", "upoordad", s)
        s = Translate("change", "cambeeoo", s)
        s = Translate("modify", "cambeeoo", s)
        s = Translate("modification", "cambeeoo", s)
        s = Translate("check", "cemnar", s)
        s = Translate("examine", "cemnar", s)
        s = Translate("study", "cemnar", s)
        s = Translate("examination", "cemnar", s)
        s = Translate("inspect", "cemnar", s)
        s = Translate("investigate", "cemnar", s)
        s = Translate("choice", "oopeeson", s)
        s = Translate("option", "oopeeson", s)
        s = Translate("choose", "coogr", s)
        s = Translate("select", "coogr", s)
        s = Translate("appoint", "coogr", s)
        s = Translate("chosen", "coogr", s)
        s = Translate("chose", "coogr", s)
        s = Translate("elect", "coogr", s)
        s = Translate("election", "coogr", s)
        s = Translate("nominate", "coogr", s)
        s = Translate("city", "setad", s)
        s = Translate("town", "setad", s)
        s = Translate("village", "setad", s)
        s = Translate("metropolis", "setad", s)
        s = Translate("urban", "setad", s)
        s = Translate("township", "setad", s)
        s = Translate("civil", "sivel", s)
        s = Translate("claim", "klaamacon", s)
        s = Translate("class", "klasaa", s)
        s = Translate("classify", "klasaa", s)
        s = Translate("category", "klasaa", s)
        s = Translate("group", "klasaa", s)
        s = Translate("party", "klasaa", s)
        s = Translate("gathering", "klasaa", s)
        s = Translate("categorize", "klasaa", s)
        s = Translate("clear", "klaar", s)
        s = Translate("plain", "klaar", s)
        s = Translate("nature", "klaar", s)
        s = Translate("natural", "klaar", s)
        s = Translate("native", "klaar", s)
        s = Translate("understandable", "klaar", s)
        s = Translate("lucid", "klaar", s)
        s = Translate("perspicuous", "klaar", s)
        s = Translate("clearly", "klaar", s)
        s = Translate("close", "klooree", s)
        s = Translate("near", "klooree", s)
        s = Translate("shut", "klooree", s)
        s = Translate("closed", "klooree", s)
        s = Translate("seal", "klooree", s)
        s = Translate("coach", "kooendoor", s)
        s = Translate("trainer", "kooendoor", s)
        s = Translate("cold", "cooeea", s)
        s = Translate("freeze", "cooeea", s)
        s = Translate("freezing", "cooeea", s)
        s = Translate("cool", "cooeea", s)
        s = Translate("chill", "cooeea", s)
        s = Translate("chilly", "cooeea", s)
        s = Translate("frigid", "cooeea", s)
        s = Translate("frost", "cooeea", s)
        s = Translate("frosty", "cooeea", s)
        s = Translate("collection", "kelekgr", s)
        s = Translate("collect", "kelekgr", s)
        s = Translate("gather", "kelekgr", s)
        s = Translate("college", "kolegsii", s)
        s = Translate("university", "kolegsii", s)
        s = Translate("school", "kolegsii", s)
        s = Translate("institute", "kolegsii", s)
        s = Translate("institution", "kolegsii", s)
        s = Translate("schoolhouse", "kolegsii", s)
        s = Translate("education", "kolegsii", s)
        s = Translate("color", "kolroosa", s)
        s = Translate("colour", "kolroosa", s)
        s = Translate("colorful", "kolroosa", s)
        s = Translate("colourful", "kolroosa", s)
        s = Translate("commercial", "komuunseeo", s)
        s = Translate("advertize", "komuunseeo", s)
        s = Translate("ad", "komuunseeo", s)
        s = Translate("announcement", "komuunseeo", s)
        s = Translate("message", "komuunseeo", s)
        s = Translate("common", "kumuun", s)
        s = Translate("mutual", "kumuun", s)
        s = Translate("usual", "kumuun", s)
        s = Translate("ordinary", "kumuun", s)
        s = Translate("regular", "kumuun", s)
        s = Translate("general", "kumuun", s)
        s = Translate("normal", "kumuun", s)
        s = Translate("familiar", "kumuun", s)
        s = Translate("typical", "kumuun", s)
        s = Translate("universal", "kumuun", s)
        s = Translate("popular", "kumuun", s)
        s = Translate("prevalent", "kumuun", s)
        s = Translate("widespread", "kumuun", s)
        s = Translate("traditional", "kumuun", s)
        s = Translate("compare", "kumpard", s)
        s = Translate("contrast", "kumpard", s)
        s = Translate("collate", "kumpard", s)
        s = Translate("differentiate", "kumpard", s)
        s = Translate("machine", "kumuudor", s)
        s = Translate("applicance", "kumuudor", s)
        s = Translate("contraption", "kumuudor", s)
        s = Translate("device", "kumuudor", s)
        s = Translate("engine", "kumuudor", s)
        s = Translate("computer", "kumuudor", s)
        s = Translate("device", "kumuudor", s)
        s = Translate("electronic", "kumuudor", s)
        s = Translate("mainframe", "kumuudor", s)
        s = Translate("netbook", "kumuudor", s)
        s = Translate("laptop", "kumuudor", s)
        s = Translate("terminal", "kumuudor", s)
        s = Translate("concern", "kunsoon", s)
        s = Translate("worry", "kunsoon", s)
        s = Translate("anxious", "kunsoon", s)
        s = Translate("restless", "kunsoon", s)
        s = Translate("uneasy", "kunsoon", s)
        s = Translate("unquietude", "kunsoon", s)
        s = Translate("condition", "kundesoon", s)
        s = Translate("shape", "kundesoon", s)
        s = Translate("conference", "kunfrseea", s)
        s = Translate("seminar", "kunfrseea", s)
        s = Translate("consumer", "kunsuuiidor", s)
        s = Translate("contain", "kunteenaa", s)
        s = Translate("hold", "kunteenaa", s)
        s = Translate("restrain", "kunteenaa", s)
        s = Translate("forbear", "kunteenaa", s)
        s = Translate("refrain", "kunteenaa", s)
        s = Translate("continue", "kuntenard", s)
        s = Translate("pursue", "kuntenard", s)
        s = Translate("endure", "kuntenard", s)
        s = Translate("maintain", "kuntenard", s)
        s = Translate("cost", "kostoo", s)
        s = Translate("price", "kostoo", s)
        s = Translate("expense", "kostoo", s)
        s = Translate("rate", "kostoo", s)
        s = Translate("fee", "kostoo", s)
        s = Translate("carfare", "kostoo", s)
        s = Translate("field", "kuniies", s)
        s = Translate("grassland", "kuniies", s)
        s = Translate("pasture", "kuniies", s)
        s = Translate("pastureland", "kuniies", s)
        s = Translate("countryside", "kuniies", s)
        s = Translate("camp", "kuniies", s)
        s = Translate("ground", "kuniies", s)
        s = Translate("country", "kuniies", s)
        s = Translate("nation", "kuniies", s)
        s = Translate("land", "kuniis", s)
        s = Translate("couple", "karaaha", s)
        s = Translate("pair", "karaaha", s)
        's = Translate("two", "karaaha", s)
        s = Translate("peer", "karaaha", s)
        s = Translate("par", "karaaha", s)
        s = Translate("mate", "karaaha", s)
        s = Translate("twosome", "karaaha", s)
        s = Translate("course", "koorsoo", s)
        s = Translate("trend", "koorsoo", s)
        s = Translate("path", "koorsoo", s)
        s = Translate("court", "koortaa", s)
        s = Translate("tribunal", "koortaa", s)
        s = Translate("judicature", "koortaa", s)
        s = Translate("courtroom", "koortaa", s)
        s = Translate("cover", "kuvbr", s)
        s = Translate("drape", "kuvbr", s)
        s = Translate("blanket", "kuvbr", s)
        s = Translate("conceal", "kuvbr", s)
        s = Translate("hide", "kuvbr", s)
        s = Translate("cloak", "kuvbr", s)
        s = Translate("covering", "kuvbr", s)
        s = Translate("sheath", "kuvbr", s)
        s = Translate("overlay", "kuvbr", s)
        s = Translate("crime", "kriimaan", s)
        s = Translate("felony", "kriimaan", s)
        s = Translate("misdeed", "kriimaan", s)
        s = Translate("delinquency", "kriimaan", s)
        s = Translate("malfeasance", "kriimaan", s)
        s = Translate("misdemeanor", "kriimaan", s)
        s = Translate("unlawful", "kriimaan", s)
        s = Translate("illegal", "kriimaan", s)
        s = Translate("culture", "kultuura", s)
        s = Translate("cultural", "kultuura", s)
        s = Translate("civilization", "kultuura", s)
        s = Translate("cup", "kusoo", s)
        s = Translate("bowl", "kusoo", s)
        s = Translate("teacup", "kusoo", s)
        s = Translate("beaker", "kusoo", s)
        s = Translate("current", "keresta", s)
        s = Translate("modern", "keresta", s)
        s = Translate("present", "keresta", s)
        s = Translate("present-day", "keresta", s)
        s = Translate("customer", "kusliintaa", s)
        s = Translate("client", "kusliintaa", s)
        s = Translate("buyer", "kusliintaa", s)
        s = Translate("purchaser", "kusliintaa", s)
        s = Translate("patron", "kusliintaa", s)
        s = Translate("shopper", "kusliintaa", s)
        s = Translate("subscriber", "kusliintaa", s)
        s = Translate("cut", "kutoor", s)
        s = Translate("slice", "kutoor", s)
        s = Translate("chop", "kutoor", s)
        s = Translate("sever", "kutoor", s)
        s = Translate("slash", "kutoor", s)
        s = Translate("gash", "kutoor", s)
        s = Translate("lacerate", "kutoor", s)
        s = Translate("slit", "kutoor", s)
        s = Translate("graze", "kutoor", s)
        s = Translate("lance", "kutoor", s)
        s = Translate("incise", "kutoor", s)
        s = Translate("penetrate", "kutoor", s)
        s = Translate("data", "daatoo", s)
        s = Translate("info", "daatoo", s)
        s = Translate("information", "daatoo", s)
        s = Translate("news", "daatoo", s)
        s = Translate("givens", "daatoo", s)
        s = Translate("facts", "daatoo", s)
        s = Translate("fact", "daatoo", s)
        s = Translate("specifics", "daatoo", s)
        s = Translate("input", "daatoo", s)
        s = Translate("details", "daatoo", s)
        s = Translate("detail", "daatoo", s)
        s = Translate("particulars", "", s)
        s = Translate("decade", "dekada", s)
        s = Translate("decide", "deesedr", s)
        s = Translate("resolve", "deesedr", s)
        s = Translate("determine", "deesedr", s)
        s = Translate("decision", "deesedr", s)
        s = Translate("deep", "deeunda", s)
        s = Translate("lower", "deeunda", s)
        s = Translate("gaping", "deeunda", s)
        s = Translate("defense", "deefensa", s)
        s = Translate("guard", "deefensa", s)
        s = Translate("protect", "deefensa", s)
        s = Translate("shield", "deefensa", s)
        s = Translate("safeguard", "deefensa", s)
        s = Translate("prevention", "deefensa", s)
        s = Translate("fortify", "deefensa", s)
        s = Translate("fortification", "deefensa", s)
        s = Translate("barricade", "deefensa", s)
        s = Translate("degree", "degradoo", s)
        s = Translate("grade", "degradoo", s)
        s = Translate("extent", "degradoo", s)
        s = Translate("rank", "degradoo", s)
        ' s = Translate("standard", "degradoo", s)
        s = Translate("diploma", "degradoo", s)
        s = Translate("describe", "deskrebr", s)
        s = Translate("description", "deskrebr", s)
        s = Translate("explain", "deskrebr", s)
        s = Translate("explaination", "deskrebr", s)
        s = Translate("portray", "deskrebr", s)
        s = Translate("delineate", "deskrebr", s)
        s = Translate("grow", "devrooya", s)
        s = Translate("develop", "devrooya", s)
        s = Translate("growth", "devrooya", s)
        s = Translate("expand", "devrooya", s)
        s = Translate("increase", "devrooya", s)
        s = Translate("inflate", "", s)
        s = Translate("inflation", "", s)
        s = Translate("amplify", "", s)
        s = Translate("amplification", "", s)
        s = Translate("formulate", "devrooya", s)
        s = Translate("development", "devrooya", s)
        s = Translate("improve", "devrooya", s)
        s = Translate("benefit", "devrooya", s)
        s = Translate("upgrade", "devrooya", s)
        s = Translate("enhanced", "devrooya", s)
        s = Translate("enhance", "devrooya", s)
        s = Translate("progress", "devrooya", s)
        s = Translate("food", "foona", s)
        s = Translate("dinner", "foona", s)
        s = Translate("meal", "foona", s)
        s = Translate("breakfast", "foona", s)
        s = Translate("supper", "foona", s)
        s = Translate("eat", "foona", s)
        s = Translate("eating", "foona", s)
        s = Translate("discuss", "desardoo", s)
        s = Translate("discussion", "desardoo", s)
        s = Translate("doctor", "docoores", s)
        s = Translate("physician", "docoores", s)
        s = Translate("medic", "docoores", s)
        s = Translate("surgeon", "docoores", s)
        s = Translate("doc", "docoores", s)
        s = Translate("nurse", "docoores", s)
        s = Translate("healer", "docoores", s)
        s = Translate("caretaker", "docoores", s)
        s = Translate("carer", "docoores", s)
        s = Translate("pcp", "docoores", s)
        s = Translate("dog", "doda", s)
        s = Translate("wolf", "doda", s)
        s = Translate("tyke", "doda", s)
        s = Translate("pooch", "doda", s)
        s = Translate("door", "doota", s)
        s = Translate("doorway", "doota", s)
        s = Translate("gate", "doota", s)
        s = Translate("gateway", "doota", s)
        s = Translate("entrance", "doota", s)
        s = Translate("entryway", "doota", s)
        s = Translate("opening", "doota", s)
        s = Translate("open", "doota", s)
        s = Translate("exit", "doota", s)
        s = Translate("dream", "dreenyoo", s)
        s = Translate("vision", "dreenyoo", s)
        s = Translate("daydream", "dreenyo", s)
        s = Translate("fantasy", "dreenyo", s)
        s = Translate("drive", "driiuusr", s)
        s = Translate("lead", "driiuusr", s)
        s = Translate("drop", "draiida", s)
        s = Translate("fall", "draiida", s)
        s = Translate("trip", "draiida", s)
        s = Translate("hang", "draiida", s)
        s = Translate("collaspe", "draiida", s)
        s = Translate("plunge", "draiida", s)
        s = Translate("drug", "drumentoo", s)
        s = Translate("medicine", "drumentoo", s)
        s = Translate("medication", "drumentoo", s)
        s = Translate("medical", "drumentoo", s)
        s = Translate("narcotic", "drumentoo", s)
        s = Translate("during", "duuraanta", s)
        s = Translate("through", "duuraanta", s)
        s = Translate("each", "eesaada", s)
        s = Translate("every", "eesaada", s)
        s = Translate("edge", "bordaa", s)
        s = Translate("border", "bordaa", s)
        s = Translate("rim", "bordaa", s)
        s = Translate("brink", "bordaa", s)
        s = Translate("verge", "bordaa", s)
        s = Translate("effect", "eefektoo", s)
        s = Translate("impact", "eefektoo", s)
        s = Translate("result", "eefektoo", s)
        s = Translate("consequence", "eefektoo", s)
        s = Translate("finish", "eefen", s)
        s = Translate("terminate", "eefen", s)
        s = Translate("end", "eefen", s)
        s = Translate("final", "eefen", s)
        s = Translate("ending", "eefen", s)
        s = Translate("last", "eefen", s)
        s = Translate("energy", "enrgeea", s)
        s = Translate("vigor", "enrgeea", s)
        s = Translate("liveliness", "enrgeea", s)
        s = Translate("enjoy", "hapfruu", s)
        s = Translate("happy", "hapfruu", s)
        s = Translate("glad", "hapfruu", s)
        s = Translate("delight", "hapfruu", s)
        s = Translate("rejoice", "hapfruu", s)
        s = Translate("pleasant", "hapfruu", s)
        s = Translate("pleasure", "hapfruu", s)
        s = Translate("bask", "hapfruu", s)
        s = Translate("joy", "hapfruu", s)
        s = Translate("enough", "eenufiin", s)
        s = Translate("sufficient", "eenufiin", s)
        s = Translate("adequate", "eenufiin", s)
        s = Translate("plenty", "eenufiin", s)
        s = Translate("ample", "eenufiin", s)
        s = Translate("entire", "entodoo", s)
        s = Translate("whole", "entodoo", s)
        s = Translate("full", "entodoo", s)
        s = Translate("complete", "entodoo", s)
        s = Translate("total", "entodoo", s)
        s = Translate("overall", "entodoo", s)
        s = Translate("absolute", "entodoo", s)
        s = Translate("filled", "", s)
        s = Translate("brimming", "", s)
        s = Translate("brimful", "", s)
        s = Translate("environment", "enviiemta", s)
        s = Translate("territory", "enviiemta", s)
        s = Translate("territories", "enviiemta", s)
        s = Translate("habitat", "enviiemta", s)
        s = Translate("surrounding", "enviiemta", s)
        s = Translate("surroundings", "enviiemta", s)
        s = Translate("conditions", "enviiemta", s)
        s = Translate("environmental", "enviiemta", s)
        s = Translate("especially", "kumuuntaa", s)
        s = Translate("mainly", "kumuuntaa", s)
        s = Translate("mostly", "kumuuntaa", s)
        s = Translate("principally", "kumuuntaa", s)
        s = Translate("largely", "kumuuntaa", s)
        s = Translate("substantially", "kumuuntaa", s)
        s = Translate("particularly", "kumuuntaa", s)
        s = Translate("primarily", "kumuuntaa", s)
        s = Translate("generally", "kumuuntaa", s)
        s = Translate("usually", "kumuuntaa", s)
        s = Translate("typically", "kumuuntaa", s)
        s = Translate("specially", "kumuuntaa", s)
        s = Translate("specifically", "kumuuntaa", s)
        s = Translate("exclusively", "kumuuntaa", s)
        s = Translate("explicitly", "kumuuntaa", s)
        s = Translate("expressly", "kumuuntaa", s)
        s = Translate("event", "eevantoo", s)
        s = Translate("occurance", "eevantoo", s)
        s = Translate("ever", "evmpraa", s)
        s = Translate("forever", "evmpraa", s)
        s = Translate("eternally", "evmpraa", s)
        s = Translate("eternal", "evmpraa", s)
        s = Translate("continually", "evmpraa", s)
        s = Translate("constant", "evmpraa", s)
        s = Translate("always", "evmpraa", s)
        s = Translate("endless", "evmpraa", s)
        s = Translate("endlessly", "evmpraa", s)
        s = Translate("prepetually", "evmpraa", s)
        s = Translate("incessantly", "evmpraa", s)
        s = Translate("incessant", "evmpraa", s)
        s = Translate("unremittingly", "evmpraa", s)
        s = Translate("nonstop", "evmpraa", s)
        s = Translate("evidence", "evenca", s)
        s = Translate("proof", "evenca", s)
        s = Translate("proove", "evenca", s)
        s = Translate("exactly", "xakmant", s)
        s = Translate("precise", "xakmant", s)
        s = Translate("precisely", "xakmant", s)
        s = Translate("entirely", "xakmant", s)
        s = Translate("absolutely", "xakmant", s)
        s = Translate("completely", "xakmant", s)
        s = Translate("totally", "xakmant", s)
        s = Translate("correct", "xakmant", s)
        s = Translate("correctly", "xakmant", s)
        s = Translate("accurate", "xakmant", s)
        s = Translate("accurately", "xakmant", s)
        s = Translate("example", "xamploo", s)
        s = Translate("sample", "xamploo", s)
        s = Translate("illustration", "xamploo", s)
        s = Translate("comparison", "xamploo", s)
        s = Translate("expect", "xpar", s)
        s = Translate("await", "xpar", s)
        s = Translate("hope", "xpar", s)
        s = Translate("predict", "xpar", s)
        s = Translate("forecast", "xpar", s)
        s = Translate("envisage", "xpar", s)
        s = Translate("envision", "xpar", s)
        s = Translate("experience", "xparseea", s)
        s = Translate("undergo", "xparseea", s)
        s = Translate("expert", "xpart", s)
        s = Translate("pro", "xpart", s)
        s = Translate("master", "xpart", s)
        s = Translate("eye", "iihoo", s)
        s = Translate("eyeball", "iihoo", s)
        s = Translate("peeper", "iihoo", s)
        s = Translate("face", "faara", s)
        s = Translate("factor", "faoont", s)
        s = Translate("element", "faoont", s)
        s = Translate("component", "faoont", s)
        s = Translate("ingredient", "faoont", s)
        s = Translate("characteristic", "faoont", s)
        s = Translate("consideration", "faoont", s)
        s = Translate("circumstance", "faoont", s)
        s = Translate("fail", "fayr", s)
        s = Translate("failure", "fayr", s)
        s = Translate("lose", "fayr", s)
        s = Translate("miss", "fayr", s)
        s = Translate("error", "fayr", s)
        s = Translate("fault", "fayr", s)
        s = Translate("malfunction", "fayr", s)
        s = Translate("unsuccess", "fayr", s)
        s = Translate("unsuccessful", "fayr", s)
        s = Translate("success", "aafayr", s)
        s = Translate("finally", "aafayr", s)
        s = Translate("eventually", "aafayr", s)
        s = Translate("feel", "feesaashon", s)
        s = Translate("discern", "feesaashon", s)
        s = Translate("feeling", "feesaashon", s)
        s = Translate("few", "fwas", s)
        s = Translate("handfull", "fwas", s)
        s = Translate("infrequent", "fwas", s)
        s = Translate("frequent", "afwas", s)
        s = Translate("often", "afwas", s)

        s = Translate("fight", "fiicha", s)
        s = Translate("brawl", "fiicha", s)
        s = Translate("figure", "figuur", s)
        s = Translate("fill", "feyan", s)
        s = Translate("refill", "feyan", s)
        s = Translate("film", "moliisa", s)
        s = Translate("movie", "moliisa", s)
        s = Translate("finger", "fengdo", s)
        s = Translate("fire", "fiieegoo", s)
        s = Translate("blaze", "fiieegoo", s)
        s = Translate("fireplace", "fiieegoo", s)
        s = Translate("burn", "fiieedad", s)
        s = Translate("burning", "fiieedad", s)
        s = Translate("scorch", "fiieedad", s)
        s = Translate("sear", "fiieedad", s)
        s = Translate("hard", "ferma", s)
        s = Translate("firm", "ferma", s)
        s = Translate("strong", "ferma", s)
        s = Translate("force", "ferma", s)
        s = Translate("brute", "ferme", s)
        s = Translate("solid", "ferma", s)
        s = Translate("resistant", "ferma", s)
        s = Translate("dense", "ferma", s)
        s = Translate("stiff", "ferma", s)
        s = Translate("rigid", "ferma", s)
        s = Translate("strength", "ferma", s)
        s = Translate("tough", "ferma", s)
        s = Translate("fish", "fez", s)
        s = Translate("flooring", "floosoo", s)
        s = Translate("floor", "floosoo", s)
        s = Translate("fly", "fliiar", s)
        s = Translate("flight", "fliiar", s)
        s = Translate("flying", "fliiar", s)
        s = Translate("soar", "fliiar", s)
        s = Translate("hover", "fliiar", s)
        s = Translate("levitate", "fliiar", s)
        s = Translate("focus", "fooshon", s)
        s = Translate("concentrate", "fooshon", s)
        s = Translate("focalise", "fooshon", s)
        s = Translate("focusing", "fooshon", s)
        s = Translate("following", "falguur", s)
        s = Translate("follow", "falguur", s)
        s = Translate("accompany", "falguur", s)
        s = Translate("foot", "fuutaa", s)
        s = Translate("foreign", "foortor", s)
        s = Translate("alien", "foortor", s)
        s = Translate("external", "foortor", s)
        s = Translate("extraterrestrial", "foortor", s)
        s = Translate("foreigner", "foortor", s)
        s = Translate("forget", "foordar", s)
        s = Translate("disremember", "foordar", s)
        s = Translate("remember", "afoordar", s)
        s = Translate("memory", "afoordar", s)
        s = Translate("recall", "afoordar", s)
        s = Translate("recollect", "afoordar", s)
        s = Translate("form", "foormar", s)
        s = Translate("shape", "foormar", s)
        s = Translate("configuration", "foormar", s)
        s = Translate("formation", "foormar", s)
        s = Translate("appearance", "foormar", s)
        s = Translate("outline", "foormar", s)
        s = Translate("forward", "foorentaa", s)
        s = Translate("onward", "foorentaa", s)
        s = Translate("ahead", "foorentaa", s)
        s = Translate("onwards", "foorentaa", s)
        s = Translate("further", "foorentaa", s)
        s = Translate("free", "fraates", s)
        s = Translate("loose", "fraates", s)
        s = Translate("release", "fraates", s)
        s = Translate("unchain", "fraates", s)
        s = Translate("unleash", "fraates", s)
        s = Translate("front", "fraataa", s)
        s = Translate("leading", "fraataa", s)
        s = Translate("lead", "fraataa", s)
        s = Translate("foremost", "fraataa", s)
        s = Translate("foreground", "fraataa", s)
        s = Translate("anterior", "fraataa", s)
        s = Translate("fore", "fraataa", s)
        s = Translate("game", "gaagoo", s)
        s = Translate("entertainment", "gaagoo", s)
        s = Translate("amusement", "gaagoo", s)
        s = Translate("recreation", "gaagoo", s)
        s = Translate("fun", "gaagoo", s)
        s = Translate("garden", "gardeen", s)
        s = Translate("lawn", "gardeen", s)
        s = Translate("give", "gudar", s)
        s = Translate("offer", "gudar", s)
        s = Translate("glass", "glaasoo", s)
        s = Translate("goal", "gool", s)
        s = Translate("task", "gool", s)
        s = Translate("mission", "gool", s)
        s = Translate("assignment", "gool", s)
        s = Translate("objective", "gool", s)
        s = Translate("aspiration", "gool", s)
        s = Translate("aspire", "gool", s)
        s = Translate("intention", "gool", s)
        s = Translate("intent", "gool", s)
        s = Translate("plan", "gool", s)
        s = Translate("purpose", "gool", s)
        s = Translate("ambition", "gool", s)
        s = Translate("want", "wasaaoo", s)
        s = Translate("desire", "wasaaoo", s)
        s = Translate("wish", "wasaaoo", s)
        s = Translate("yearn", "wasaaoo", s)
        s = Translate("yearning", "wasaaoo", s)
        s = Translate("crave", "wasaaoo", s)
        s = Translate("craving", "wasaaoo", s)
        s = Translate("envy", "wasaaoo", s)
        s = Translate("envious", "wasaaoo", s)
        s = Translate("gun", "gustola", s)
        s = Translate("firearm", "gustola", s)
        s = Translate("pistol", "gustola", s)
        s = Translate("rifle", "gustola", s)
        s = Translate("shotgun", "gustola", s)
        s = Translate("weapon", "gustola", s)
        s = Translate("hair", "harloo", s)
        s = Translate("fur", "harloo", s)
        s = Translate("fleece", "harloo", s)
        s = Translate("pelt", "harloo", s)
        s = Translate("mane", "harloo", s)
        s = Translate("hand", "hanoo", s)
        s = Translate("palm", "hanoo", s)
        s = Translate("paw", "hanoo", s)
        s = Translate("mitt", "hanoo", s)
        s = Translate("swing", "swaashun", s)
        s = Translate("sway", "swaashun", s)
        s = Translate("happen", "vantoo", s)
        s = Translate("occur", "vantoo", s)
        s = Translate("befall", "vantoo", s)
        s = Translate("head", "hebza", s)
        s = Translate("skull", "hebza", s)
        s = Translate("noggin", "hebza", s)
        s = Translate("listen", "hooeed", s)
        s = Translate("hear", "hooeed", s)
        s = Translate("ear", "hooeed", s)
        s = Translate("apprehend", "hooeed", s)
        s = Translate("sound", "hooeed", s)
        s = Translate("heart", "hartzoon", s)
        s = Translate("compassion", "hartzoon", s)
        s = Translate("generous", "hartzoon", s)
        s = Translate("affection", "hartzoon", s)
        s = Translate("heat", "heelor", s)
        s = Translate("hot", "heelor", s)
        s = Translate("warm", "heelor", s)
        s = Translate("warmth", "heelor", s)
        s = Translate("mugginess", "heelor", s)
        s = Translate("humid", "heelor", s)
        s = Translate("fever", "heelor", s)
        s = Translate("reheat", "heelor", s)
        s = Translate("heavy", "hevsaada", s)
        s = Translate("weight", "hevsaada", s)
        s = Translate("weigh", "hevsaada", s)
        s = Translate("hefty", "hevsaada", s)
        s = Translate("ponderous", "hevsaada", s)
        s = Translate("stocky", "hevsaada", s)
        s = Translate("help", "helda", s)
        s = Translate("assist", "helda", s)
        s = Translate("assistance", "helda", s)
        s = Translate("aid", "helda", s)
        s = Translate("support", "helda", s)
        s = Translate("succor", "helda", s)
        s = Translate("tall", "talta", s)
        s = Translate("lofty", "talta", s)
        s = Translate("towering", "talta", s)
        s = Translate("elevated", "talta", s)
        s = Translate("elevate", "talta", s)
        s = Translate("home", "hoosa", s)
        s = Translate("house", "hoosa", s)
        s = Translate("residence", "hoosa", s)
        s = Translate("apartment", "hoosa", s)
        s = Translate("cottage", "hoosa", s)
        s = Translate("accommodations", "hoosa", s)
        s = Translate("quarters", "hoosa", s)
        s = Translate("rooms", "hoosa", s)
        s = Translate("dwelling-place", "hoosa", s)
        s = Translate("hotel", "hootaal", s)
        s = Translate("guesthouse", "hootaal", s)
        s = Translate("motel", "hootaal", s)
        s = Translate("lodge", "hootaal", s)
        s = Translate("lodging", "hootaal", s)
        s = Translate("idea", "iidaaa", s)
        s = Translate("concept", "iidaaa", s)
        s = Translate("invent", "iidaaa", s)
        s = Translate("imagine", "iidaaa", s)
        s = Translate("proposal", "iidaaa", s)
        s = Translate("identify", "iidaanesar", s)
        s = Translate("identity", "iidaanesar", s)
        s = Translate("recognize", "iidaanesar", s)
        s = Translate("pinpoint", "iidaanesar", s)
        s = Translate("know", "noobar", s)
        s = Translate("knowledge", "noobar", s)
        s = Translate("realize", "noobar", s)
        s = Translate("mind", "noobar", s)
        s = Translate("image", "emaagan", s)
        s = Translate("picture", "emaagan", s)
        s = Translate("drawing", "emaagan", s)
        s = Translate("portrayal", "emaagan", s)
        s = Translate("representation", "emaagan", s)
        s = Translate("statue", "emaagan", s)
        s = Translate("sketch", "emaagan", s)
        s = Translate("painting", "emaagan", s)
        s = Translate("portrait", "emaagan", s)
        s = Translate("statuette", "emaagan", s)
        s = Translate("important", "empoortaa", s)
        s = Translate("essential", "empoortaa", s)
        s = Translate("valuable", "empoortaa", s)
        s = Translate("vital", "empoortaa", s)
        s = Translate("prudent", "empoortaa", s)
        s = Translate("significant", "empoortaa", s)
        s = Translate("fundamental", "empoortaa", s)
        s = Translate("necessary", "empoortaa", s)
        s = Translate("indispensable", "empoortaa", s)
        s = Translate("relevant", "empoortaa", s)
        s = Translate("pertinent", "empoortaa", s)
        s = Translate("paramount", "empoortaa", s)
        s = Translate("crucial", "empoortaa", s)
        s = Translate("imperative", "empoortaa", s)
        s = Translate("preeminent", "empoortaa", s)
        s = Translate("major", "empoortaa", s)
        s = Translate("include", "enkluued", s)
        s = Translate("incorporate", "enkluued", s)
        s = Translate("contain", "enkluued", s)
        s = Translate("involve", "enkluued", s)
        s = Translate("encompass", "enkluued", s)
        s = Translate("including", "enkluued", s)
        s = Translate("indicate", "endeecar", s)
        s = Translate("specify", "endeecar", s)
        s = Translate("stipulate", "endeecar", s)
        s = Translate("instead", "ensluugar", s)
        s = Translate("alternative", "ensluugar", s)
        s = Translate("substitute", "ensluugar", s)
        s = Translate("alternatively", "ensluugar", s)
        s = Translate("alternately", "ensluugar", s)
        s = Translate("otherwise", "ensluugar", s)
        s = Translate("interest", "entarsedtaa", s)
        s = Translate("interesting", "entarsedtaa", s)
        s = Translate("enthusiasm", "entarsedtaa", s)
        s = Translate("curiosity", "entarsedtaa", s)
        s = Translate("international", "entarshunel", s)
        s = Translate("issue", "eshuuma", s)
        s = Translate("problem", "eshuuma", s)
        s = Translate("topic", "eshuuma", s)
        s = Translate("item", "eetoo", s)
        s = Translate("thing", "eetoo", s)
        s = Translate("stuff", "eetoo", s)
        s = Translate("object", "eetoo", s)
        s = Translate("piece", "eetoo", s)
        s = Translate("join", "joosaa", s)
        s = Translate("unite", "joosaa", s)
        s = Translate("attached", "joosaa", s)
        s = Translate("attach", "joosaa", s)
        s = Translate("connect", "joosaa", s)
        s = Translate("merge", "joosaa", s)
        s = Translate("conjoin", "joosaa", s)
        s = Translate("keep", "keetnar", s)
        s = Translate("remain", "keetnar", s)
        s = Translate("key", "keeyaa", s)
        s = Translate("kill", "kilt", s)
        s = Translate("murder", "", s)
        s = Translate("type", "kiipee", s)
        s = Translate("brand", "kiipee", s)
        s = Translate("genre", "kiipee", s)
        s = Translate("kitchen", "ketshnaa", s)
        s = Translate("language", "langooma", s)
        s = Translate("late", "lardaa", s)
        s = Translate("tardy", "lardaa", s)
        s = Translate("overdue", "lardaa", s)
        s = Translate("delay", "lardooa", s)
        s = Translate("later", "largooa", s)
        s = Translate("afterwards", "largooa", s)
        s = Translate("afterward", "largooa", s)
        s = Translate("postpone", "largooa", s)
        s = Translate("laugh", "riifruu", s)
        s = Translate("chuckle", "riifruu", s)
        s = Translate("laughing", "riifruu", s)
        s = Translate("chuckling", "riifruu", s)
        s = Translate("laughs", "riifruu", s)
        s = Translate("chuckles", "riifruu", s)
        s = Translate("snicker", "riifruu", s)
        s = Translate("chortle", "riifruu", s)
        s = Translate("guffaw", "riifruu", s)
        s = Translate("giggle", "riifruu", s)
        s = Translate("titter", "riifruu", s)
        s = Translate("snigger", "riifruu", s)
        s = Translate("lay", "liitars", s)
        s = Translate("laid", "liitars", s)
        s = Translate("left", "lefrda", s)
        s = Translate("right", "riita", s)
        s = Translate("leg", "laana", s)
        s = Translate("limb", "laana", s)
        s = Translate("letter", "lrtaa", s)
        s = Translate("level", "levaal", s)
        s = Translate("flat", "levaal", s)
        s = Translate("smooth", "levaal", s)
        s = Translate("lie", "liira", s)
        s = Translate("untruth", "liira", s)
        s = Translate("deceive", "liira", s)
        s = Translate("deception", "liira", s)
        s = Translate("truth", "aliira", s)
        s = Translate("candor", "aliira", s)
        s = Translate("honest", "aliira", s)
        s = Translate("honesty", "aliira", s)
        s = Translate("truthful", "aliira", s)
        s = Translate("light", "", s)
        s = Translate("bright", "", s)
        s = Translate("illuminated", "", s)
        s = Translate("illuminate", "", s)
        s = Translate("like", "liiuusta", s)
        s = Translate("love", "luvor", s)
        s = Translate("passion", "luvor", s)
        s = Translate("cherish", "luvor", s)
        s = Translate("probable", "proovavlaa", s)
        s = Translate("likely", "proovavlaa", s)
        s = Translate("expected", "proovavlaa", s)
        s = Translate("possible", "proovavlaa", s)
        s = Translate("plausible", "proovavlaa", s)
        s = Translate("anticipated", "proovavlaa", s)
        s = Translate("forseeable", "proovavlaa", s)
        s = Translate("line", "liinaa", s)
        s = Translate("underline", "liinaa", s)
        s = Translate("list", "lesta", s)
        s = Translate("directory", "lesta", s)
        s = Translate("loss", "losaa", s)
        s = Translate("main", "maapel", s)
        s = Translate("market", "markaadoo", s)
        s = Translate("store", "markaadoo", s)
        s = Translate("marry", "marmonoo", s)
        s = Translate("marriage", "marmonoo", s)
        s = Translate("material", "matreea", s)
        s = Translate("matter", "matreea", s)
        s = Translate("substance", "matreea", s)
        s = Translate("mean", "mala", s)
        s = Translate("measure", "meshiida", s)
        s = Translate("media", "meedaoon", s)
        s = Translate("video", "meedaoon", s)
        s = Translate("mention", "menshonr", s)
        s = Translate("military", "miletar", s)
        s = Translate("army", "miletar", s)
        s = Translate("model", "modaloo", s)
        s = Translate("pattern", "modaloo", s)
        s = Translate("actor", "modaloo", s)
        s = Translate("standard", "modaloo", s)
        s = Translate("exemplar", "modaloo", s)
        s = Translate("guideline", "modaloo", s)
        s = Translate("guide", "modaloo", s)
        s = Translate("mouth", "mooka", s)
        s = Translate("jaws", "mooka", s)
        s = Translate("muzzle", "mooka", s)
        s = Translate("song", "muuseca", s)
        s = Translate("music", "muuseca", s)
        s = Translate("melody", "muuseca", s)
        s = Translate("must", "musbaa", s)
        s = Translate("should", "musbaa", s)
        s = Translate("simple", "simpaaya", s)
        s = Translate("easy", "simpaaya", s)
        s = Translate("straightforward", "simpaaya", s)
        s = Translate("elementary", "simpaaya", s)
        s = Translate("need", "musbaa", s)
        s = Translate("network", "ned", s)
        s = Translate("matrix", "ned", s)
        s = Translate("system", "ned", s)
        s = Translate("web", "ned", s)
        s = Translate("grid", "ned", s)
        s = Translate("never", "nevkaa", s)
        s = Translate("next", "nektaa", s)
        s = Translate("then", "nektaa", s)
        s = Translate("upcoming", "nektaa", s)
        s = Translate("number", "nuumaaro", s)
        s = Translate("numeral", "nuumaaro", s)
        s = Translate("integer", "nuumaaro", s)
        s = Translate("digit", "nuumaaro", s)
        s = Translate("decimal", "nuumaaro", s)
        s = Translate("oil", "oolaa", s)
        s = Translate("lube", "oolaa", s)
        s = Translate("lubricant", "oolaa", s)
        s = Translate("grease", "oolaa", s)
        s = Translate("petroleum", "oolaa", s)
        s = Translate("once", "1", s)
        s = Translate("one", "1", s)
        s = Translate("twice", "2", s)
        s = Translate("two", "2", s)
        s = Translate("third", "3", s)
        s = Translate("three", "3", s)
        s = Translate("operation", "uprashoon", s)
        s = Translate("performance", "uprashoon", s)
        s = Translate("own", "oopeea", s)
        s = Translate("possess", "oopeea", s)
        s = Translate("owner", "oopeeaa", s)
        s = Translate("pain", "paalor", s)
        s = Translate("hurt", "paalor", s)
        s = Translate("suffer", "paalor", s)
        s = Translate("agony", "paalor", s)
        s = Translate("tortue", "paalor", s)
        s = Translate("ache", "paalor", s)
        s = Translate("sore", "paalor", s)
        s = Translate("throb", "paalor", s)
        s = Translate("sting", "paalor", s)
        s = Translate("pass", "pasar", s)
        s = Translate("permit", "pasar", s)
        s = Translate("proceed", "pasar", s)
        s = Translate("wait", "paaentaa", s)
        s = Translate("patient", "paaentaa", s)
        s = Translate("patience", "paaentaa", s)
        s = Translate("peace", "peez", s)
        s = Translate("calm", "peez", s)
        s = Translate("tranquility", "peez", s)
        s = Translate("quiet", "peez", s)
        s = Translate("", "", s)
        s = Translate("", "", s)
        s = Translate("", "", s)
        s = Translate("", "", s)
        s = Translate("", "", s)
        s = Translate("", "", s)
        s = Translate("", "", s)
        s = Translate("", "", s)
        s = Translate("", "", s)
        s = Translate("", "", s)





        '...Very last...
        s = s.Replace("t", "T") : s = s.Replace("Th", "t")
        s = s.Replace("s", "S") : s = s.Replace("Sh", "s")

        s = s.Replace("ch", "c")
        s = s.Replace("ph", "f")
        s = s.Replace("qu", "q")
        ' Remove double letter, except vowels
        s = s.Replace("bb", "b").Replace("cc", "c").Replace("dd", "d").Replace("ff", "f").Replace("gg", "g").Replace("hh", "h").Replace("jj", "j").Replace("kk", "k") _
            .Replace("ll", "l").Replace("mm", "m").Replace("nn", "n").Replace("pp", "p").Replace("qq", "q").Replace("rr", "r").Replace("ss", "s").Replace("tt", "t") _
            .Replace("vv", "v").Replace("ww", "w").Replace("xx", "x").Replace("yy", "y").Replace("zz", "z")

        ' s = s.Replace("ie", "ee")

        '...Set Font...
        Try : Dim privateFonts As New System.Drawing.Text.PrivateFontCollection() : privateFonts.AddFontFile(Application.StartupPath & "\Rextonian.ttf") : Dim font As New System.Drawing.Font(privateFonts.Families(0), 14)
            me_Rextonian.Font = font : Catch ex As Exception : End Try
        Try : Dim privateFonts As New System.Drawing.Text.PrivateFontCollection() : privateFonts.AddFontFile(Application.StartupPath & "\Masonian.ttf") : Dim font As New System.Drawing.Font(privateFonts.Families(0), 14)
            me_Masonian.Font = font : Catch ex As Exception : End Try

        '...Set Textboxes...
        'Rextonian
        me_Rextonian.Text = s
        me_Masonian.Text = s
        'Pronuciation
        me_pronunciation.Text = s.Replace("aa", "a`").Replace("ee", "e`").Replace("ii", "i`").Replace("oo", "o`").Replace("uu", "u`") _
            .Replace("q", "kw").Replace("c", "ch") _
            .Replace("s", "sh").Replace("t", "th").Replace("T", "t").Replace("S", "s")

    End Sub
    Public Sub StartPhrases()
        Dim s As String = EnglishText
        s = Translate("hey man", "helaa", s)
        s = Translate("This is the", "deS", s)
        s = Translate("thank you", "taanSeeaS", s)
        s = Translate("you're welcome", "welda", s)
        s = Translate("I am", "maa", s)
        s = Translate("my name is", "maa", s)
        s = Translate("what is your name", "yoo huu", s)
        s = Translate("how are you doing", "hoomaS yoo", s)
        s = Translate("how are you", "hoomaS yoo", s)
        s = Translate("how is it going", "hoomaS yoo", s)
        s = Translate("how's it going", "hoomaS yoo", s)
        s = Translate("hows it going", "hoomaS yoo", s)
        s = Translate("what's up", "kaa uupasa", s)
        s = Translate("whats up", "kaa uupasa", s)
        s = Translate("'sup", "kaa uupasa", s)
        s = Translate("sup", "kaa uupasa", s)
        s = Translate("wassup", "kaa uupasa", s)
        s = Translate("whassup", "kaa uupasa", s)
        s = Translate("what's going on", "kaa uupasa", s)
        s = Translate("nice to meet you", "niisen meerS yoo", s)

        s = Translate("excuse me?", "pardoonoo?", s)
        s = Translate("pardon?", "pardoonoo?", s)
        s = Translate("pardon me?", "pardoonoo?", s)
        s = Translate("again please", "pardoonoo?", s)
        s = Translate("live in", "leeSedr", s)
        s = Translate("i am from", "leeSedr", s)
        s = Translate("i'm from", "leeSedr", s)
        s = Translate("wandering around", "wandlar", s)
        s = Translate("wandering about", "wandlar", s)
        s = Translate("lurking about", "wandlar", s)
        s = Translate("lurking around", "wandlar", s)
        s = Translate("solar system", "Sunol SeSTema", s)
        s = Translate("sun system", "Sunol SeSTema", s)

        s = Translate("super power", "aabilad", s)
        s = Translate("super ability", "aabilad", s)

        s = Translate("in front", "atrevlara", s)
        s = Translate("in the lead", "atrevlara", s)
        s = Translate("at the fore", "atrevlara", s)

        s = Translate("in reply", "ansondr", s)
        s = Translate("in response", "ansondr", s)

        s = Translate("comes up", "aariiSger", s)
        s = Translate("lend a hand", "helda", s)

        s = Translate("of course", "suuro", s)

        s = Translate("around the world", "entarshunel", s)

        s = Translate("what kind", "kaa kiipee", s)

        s = Translate("lie down", "liitars", s)
        s = Translate("have to", "musbaa", s)
        s = Translate("need to", "musbaa", s)
        s = Translate("not ever", "nevkaa", s)

        s = Translate("this is the", "des", s)
        s = Translate("these are the", "des", s)
        s = Translate("these are", "des", s)
        s = Translate("is the", "des", s)
        s = Translate("this is", "des", s)



        EnglishText = s
    End Sub
    Public Sub ReadDictionary()
        Try
            Dim s As String = EnglishText
            Dim DictionaryFile As String = Application.StartupPath + "\Rextonian.dic"

            Dim DictionaryString As String() = IO.File.ReadAllLines(DictionaryFile)
            ' Dim DictionaryString As String = IO.File.ReadAllText(DictionaryFile)

            ' Dim Ar() As String = DictionaryString.Split(Environment.NewLine)

            For Each sr As String In DictionaryString
                ' s is the variable to process
                Dim str1 As String = sr.Substring(0, sr.IndexOf("=")).ToString
                Dim str2 As String = sr.Substring(sr.IndexOf("=") + 1).ToString


                s = Translate(str1, str2, s)
                EnglishText = s
                '     MsgBox(s)

            Next

        Catch ex As Exception

        End Try

    End Sub
#End Region


#End Region

#Region " Animate / Expand button"

    Dim animationSpeed As Integer = 600
    Sub AnimateObject(ByVal ObjectToAnimate As Object, ByVal showObject As Boolean, ByVal IsControl As Boolean, ByVal AnimateUpwards As Boolean)
        If showObject Then
            If IsControl Then
                If AnimateUpwards Then
                    ' ObjectToAnimate.Top = Me.Height
                    ' Transition.run(ObjectToAnimate, "Top", 654, (New TransitionType_EaseInEaseOut(animationSpeed)))
                    Dim t As New Transition(New TransitionType_EaseInEaseOut(animationSpeed)) : AddHandler t.TransitionCompletedEvent, AddressOf TransitionCompleted
                    t.add(ObjectToAnimate, "Height", 677) : t.run()
                Else
                    ' ObjectToAnimate.Left = Me.Width
                    Transition.run(ObjectToAnimate, "Left", 17, (New TransitionType_EaseInEaseOut(animationSpeed)))
                End If
            Else
                '  Me.Width = 560
                Dim t As New Transition(New TransitionType_EaseInEaseOut(animationSpeed)) : AddHandler t.TransitionCompletedEvent, AddressOf TransitionCompleted
                t.add(ObjectToAnimate, "Width", 903) : t.run()
                ' Transition.run(ObjectToAnimate, "Width", 903, (New TransitionType_EaseInEaseOut(animationSpeed)))
            End If
        Else
            If IsControl Then
                If AnimateUpwards Then
                    '  Transition.run(ObjectToAnimate, "Top", 463, (New TransitionType_EaseInEaseOut(animationSpeed)))
                    Dim t As New Transition(New TransitionType_EaseInEaseOut(animationSpeed)) : AddHandler t.TransitionCompletedEvent, AddressOf TransitionCompleted
                    t.add(ObjectToAnimate, "Height", 463) : t.run()
                Else
                    Transition.run(ObjectToAnimate, "Left", Me.Width, (New TransitionType_EaseInEaseOut(animationSpeed)))
                End If
            Else
                Dim t As New Transition(New TransitionType_EaseInEaseOut(animationSpeed)) : AddHandler t.TransitionCompletedEvent, AddressOf TransitionCompleted
                t.add(ObjectToAnimate, "Width", 560) : t.run()

            End If
        End If
    End Sub
    Public Sub TransitionCompleted()
        but_Expand.Enabled = True
        but_taller.Enabled = True
    End Sub
    Private Sub but_Expand_Click(sender As Object, e As EventArgs) Handles but_Expand.Click
        but_Expand.Enabled = False
        Select Case Me.Width
            Case Is >= 903
                AnimateObject(Me, False, False, False)
                but_Expand.Text = "⯈"
            Case Is < 903
                AnimateObject(Me, True, False, False)
                but_Expand.Text = "⯇"
        End Select
    End Sub

    Private Sub but_taller_Click(sender As Object, e As EventArgs) Handles but_taller.Click
        but_taller.Enabled = False
        Select Case Me.Height
            Case Is >= 677
                AnimateObject(Me, False, True, True)
                but_taller.Text = "⯆"
            Case Is < 677
                AnimateObject(Me, True, True, True)
                but_taller.Text = "⯅"
        End Select
    End Sub


#End Region


#Region " Clear all"

    Private Sub but_Clear_Click(sender As Object, e As EventArgs) Handles but_Clear.Click
        me_English.Text = ""
        me_Rextonian.Text = ""
        me_Masonian.Text = ""
        me_pronunciation.Text = ""
    End Sub

#End Region



    Private Sub but_Copy_Click(sender As Object, e As EventArgs) Handles but_Copy.Click
        If me_Rextonian.Text <> String.Empty Then
            Clipboard.SetText(me_Rextonian.Text)
        End If
    End Sub


End Class
